Repository WVU-CS230-2023-01-Group10/GotNext, pull requests merged in 2023-03, with the labels that each got.

#7 fixed build issue
  .github/CODEOWNERS
  src/app/app.component.html
Labels: bug

#9 Add routing
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/favicon.ico
Labels: enhancement

#11 routed homepage to loginpage
  src/app/app-routing.module.ts
  src/app/home-page/home-page.component.html
Labels: enhancement

#17 made the login page better
  package-lock.json
  package.json
  src/app/login-page/login-page.component.css
  src/app/login-page/login-page.component.html
Labels: enhancement

#18 update CODEOWNERS
  .github/CODEOWNERS
Labels: documentation

#43 Ij fix component names
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/game-list-page/game-list-page.css
  src/app/game-list-page/game-list-page.html
  src/app/game-list-page/game-list-page.ts
  src/app/host-game-view-page/host-game-view-page.component.css
  src/app/host-game-view-page/host-game-view-page.component.html
  src/app/host-game-view-page/host-game-view-page.component.spec.ts
  src/app/host-game-view-page/host-game-view-page.component.ts
  src/app/player-party-page/player-party-page.ts
  src/app/user-game-view-page/user-game-view-page.component.css
  src/app/user-game-view-page/user-game-view-page.component.html
  src/app/user-game-view-page/user-game-view-page.component.spec.ts
  src/app/user-game-view-page/user-game-view-page.component.ts
  src/app/user-login-page/user-login-page.component.css
  src/app/user-login-page/user-login-page.component.html
  src/app/user-login-page/user-login-page.component.spec.ts
  src/app/user-login-page/user-login-page.component.ts
Labels: enhancement

#47 Ij update routing
  angular.json
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/home-page/home-page.component.html
  src/app/party-entry-page/party-entry-page.component.html
  src/app/party-logistics-page/party-logistics-page.component.html
  src/app/queue-page/queue-page.component.html
  src/app/user-login-page/user-login-page.component.ts
Labels: enhancement

#55 generate qr code
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/qr-page/qr-page.component.css
  src/app/qr-page/qr-page.component.html
  src/app/qr-page/qr-page.component.ts
  src/assets/IMG_4037.PNG
Labels: enhancement
